# https://meet.google.com/vxp-jaji-feg: Daily GlobalTask
name: Hello world

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: Touch file
        run: touch hello-world.txt

      - name: Set text
        run: echo 'Hello World' > hello-world.txt

      - name: Read file
        run: cat hello-world.txt

  other:
    runs-on: ubuntu-latest

    steps:
      - name: LS
        run: ls -al

  other-01:
    runs-on: ubuntu-latest
    needs: [other]

    steps:
      - name: Ls-01
        run: ls -al
